---

- hosts: tag_Name_svaranasi_private_instance
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
  - include_vars: group_vars/all.yml

  - command: /usr/local/bin/pip install -r requirements.txt
  
  - name: install the latest version of Apache
    yum:
      name: nginx
      state: present
  
  - copy: src=app.py dest=/home/ec2-user mode=0644 owner=ec2-user group=ec2-user
  - copy: src=requirements.txt dest=/home/ec2-user mode=0644 owner=ec2-user group=ec2-user
  - copy: src=nginx.conf dest=/etc/nginx mode=0644 owner=root group=root 
  - copy: src=gunicorn.conf dest=/etc/init mode=0644 owner=root group=root

  - service:
      name: nginx
      state: started

  - service:
      name: gunicorn
      state: started

