---

- hosts: tag_Name_svaranasi_private_instance
  remote_user: ec2-user

  

  tasks:
  
  - include_vars: group_vars/all

  - copy: src=app.py dest=/home/ec2-user mode=0644
  - copy: src=requirements.txt dest=/home/ec2-user mode=0644

  - command: /usr/local/bin/pip install -r requirements.txt
    become: yes
    become_user: root
