---

- hosts: tag_Name_svaranasi_private_instance
  remote_user: ec2-user
  #sudo: yes

  

  tasks:
  
  - name: Install Python Pip
      yum: name=python-pip state=latest

  - include_vars: group_vars/all

  - copy: src=app.py dest=/home/ec2-user mode=0644
  - copy: src=requirements.txt dest=/home/ec2-user mode=0644

  - pip:
      requirements: requirements.txt
